"""empty message

Revision ID: 14be3d7a5c0d
Revises: 0e05ff9bbda4
Create Date: 2020-03-04 21:15:32.087139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14be3d7a5c0d'
down_revision = '0e05ff9bbda4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_order', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sale_order', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sale_order', type_='foreignkey')
    op.drop_column('sale_order', 'client_id')
    # ### end Alembic commands ###
